### ISSUE TITLE
Fixing typo in iovxw/ksni

### ISSUE THREAD

**Issue by emirror-de** [emirror-de/openprobst#1]
**Repository**
In which repository does this bug occur?
https://github.com/iovxw/ksni

**Linked issues**
Are there already issues linked with the topic?
No

**Problem description**
Typo in Separator variant

**Checklist**
- [X] Added a link to the repository
- [X] Checked the repository for already linked issues and provided links to them
- [X] Description of expected behavior is provided
- [ ] Description of actual behavior is provided
- [ ] Screenshots or code example are inserted or linked
- [ ] Steps to reproduce are clear and tested
- [ ] The used system setup has been provided

**Comment by emirror-de** [comment]
Fixed and merged in
https://github.com/iovxw/ksni/pull/8
