### ISSUE TITLE
Upgrade gtk dependency in libayatana-appindicator-rs

### ISSUE THREAD

**Issue by emirror-de** [emirror-de/openprobst#3]
**Repository**
To which repository does this feature belong to?
https://github.com/emirror-de/libayatana-appindicator-rs

**Linked issues**
Are there already issues linked with this feature request?

**Motivation**
What problem should this feature solve in the future? Please describe short and clear, but as detailed as possible.
GTK dependency should be up to date.

**Checklist**
- [x] Added a link to the repository
- [x] Checked the repository for already linked issues and provided links to them
- [x] Clear description of the motivation
- [x] ***Added this issue to the openprobst.dev project***

**Comment by emirror-de** [comment]
Upgrade done in Release [0.1.4](https://github.com/emirror-de/libayatana-appindicator-rs/tree/0.1.4).
