### ISSUE TITLE
html5-picture does not create the required folders when using install_images_into option

### ISSUE THREAD

**Issue by emirror-de** [emirror-de/openprobst#7]
**Repository**
In which repository does this bug occur?

https://github.com/emirror-de/html5-picture

**Linked issues**
Are there already issues linked with this bug?
No.

**Expected behavior**
Please describe the expected behavior. Short and clear.

When using `install_images_into` option, the folder that is given in this option should be created automatically.

**Actual behavior**
Please describe the behavior that is making you create this issue.

The folder is not created

**To Reproduce**
1. Invoke `html5-picture assets-dev 3 -i assets

**Operating system**
What system setup are you using? Relevant program versions might be helpful as well.

Any.

**Checklist**
- [X] Added a link to the repository
- [X] Checked the repository for already linked issues and provided links to them
- [X] Description of expected behavior is provided
- [X] Description of actual behavior is provided
- [X] Steps to reproduce are clear and tested
- [X] The used system setup has been provided
- [X] ***Added this issue to the openprobst.dev project***

**Comment by emirror-de** [comment]
Has been fixed in version [0.2.2](https://github.com/emirror-de/html5-picture/releases/tag/v0.2.2)
